### ISSUE TITLE
Error running on Mac

### ISSUE THREAD

**Issue by webalchemist** [alastairparagas/cordova-minify#6]
Your hook install fine on my PC, but it threw the following error while trying to use it on a Mac.

module.js:340
    throw err;
          ^
Error: Cannot find module 'imagemin-gifsicle'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mapometer/Documents/development/mobile_app/node_modules/cordova-minify/node_modules/image-min/index.js:165:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Hook failed with error code 8: /Users/mapometer/Documents/development/mobile_app/hooks/after_prepare/minify.js

Manually installing the missing dependencies for image-min fixed the issue.

I also notice that image-min has not been updated for 6 months and that it's github page no longer exists.  Github now redirects to the page for another NPM module 'imagemin' (no dash).  This is at github.com/imagemin/imagemin.

**Comment by alastairparagas** [comment]
@webalchemist Sorry for the late response, I have been busy. I noticed that image-min has been moved to the new imagemin repository. I bumped the versions up. [You can check it out here](https://github.com/alastairparagas/cordova-minify/blob/master/package.json#L17).
